// ── MAPA COMPLETO DE CATEGORIAS PT-BR ─────────────────────────
const CAT_LABEL_MAP = {
  'global-affairs':          'Assuntos Globais',
  'news':                    'Notícias',
  'opinion':                 'Opinião',
  'editorial':               'Editorial',
  'features':                'Reportagens',
  'headlines':               'Destaques',
  'politics-and-society':    'Política',
  'geopolitics':             'Geopolítica',
  'international-affairs':   'Assuntos Internacionais',
  'international-relations': 'Relações Internacionais',
  'international-politics':  'Política Internacional',
  'world-affairs':           'Assuntos Mundiais',
  'policy':                  'Política Pública',
  'military':                'Militar',
  'ethics-and-society':      'Ética e Sociedade',
  'society-and-culture':     'Sociedade e Cultura',
  'global-economy':          'Economia Global',
  'business-and-economy':    'Negócios e Economia',
  'finances':                'Finanças',
  'financial-education':     'Educação Financeira',
  'entrepreneurship':        'Empreendedorismo',
  'shopping':                'Compras',
  'science':                 'Ciência',
  'technology':              'Tecnologia',
  'innovation':              'Inovação',
  'future-and-innovation':   'Futuro e Inovação',
  'astronomy':               'Astronomia',
  'e-auto':                  'E-Auto',
  'health':                  'Saúde',
  'well-being':              'Bem-Estar',
  'fitness':                 'Fitness',
  'personal-development':    'Desenvolvimento Pessoal',
  'motivational':            'Motivacional',
  'culture-and-history':     'Cultura e História',
  'history':                 'História',
  'history-and-philosophy':  'História e Filosofia',
  'philosophy':              'Filosofia',
  'literature':              'Literatura',
  'books':                   'Livros',
  'music':                   'Música',
  'architecture-and-art':    'Arquitetura e Arte',
  'chronicle':               'Crônica',
  'story':                   'Conto',
  'religiosity':             'Religiosidade',
  'magazine':                'Revista',
  'sports':                  'Esportes',
  'soccer':                  'Futebol',
  'tennis':                  'Tênis',
  'formula-1':               'Fórmula 1',
  'cycling':                 'Ciclismo',
  'olympic-games':           'Jogos Olímpicos',
  'pan-american-games':      'Jogos Pan-Americanos',
  'lifestyle':               'Estilo de Vida',
  'food':                    'Gastronomia',
  'tourism-and-gastronomy':  'Turismo e Gastronomia',
  'fashion':                 'Moda',
  'beauty':                  'Beleza',
  'pets':                    'Animais de Estimação',
  'agriculture':             'Agricultura',
  'education':               'Educação',
  'courses-and-careers':     'Cursos e Carreiras',
  'works':                   'Trabalho',
  'social-networks':         'Redes Sociais',
  'video-library':           'Videoteca',
  'documentaries':           'Documentários',
  'environment':             'Meio Ambiente',
  'covid-19':                'Covid-19',
  'events':                  'Eventos',
  'bicentennial':            'Bicentenário',
};

const CAT_BADGE_MAP = {
  'politics-and-society':'badge-politica','policy':'badge-politica',
  'geopolitics':'badge-politica','international-politics':'badge-politica',
  'international-relations':'badge-politica','international-affairs':'badge-politica',
  'world-affairs':'badge-politica','military':'badge-politica',
  'ethics-and-society':'badge-politica','society-and-culture':'badge-politica',
  'news':'badge-noticias','headlines':'badge-noticias',
  'global-economy':'badge-economia','business-and-economy':'badge-economia',
  'finances':'badge-economia','financial-education':'badge-economia',
  'entrepreneurship':'badge-economia','shopping':'badge-economia',
  'science':'badge-ciencia','astronomy':'badge-ciencia',
  'history':'badge-history','history-and-philosophy':'badge-history',
  'culture-and-history':'badge-culture','society-and-culture':'badge-culture',
  'literature':'badge-culture','books':'badge-culture','music':'badge-culture',
  'architecture-and-art':'badge-culture','chronicle':'badge-culture',
  'story':'badge-culture','magazine':'badge-culture','video-library':'badge-culture',
  'documentaries':'badge-culture',
  'technology':'badge-tecnologia','innovation':'badge-tecnologia',
  'future-and-innovation':'badge-tecnologia','e-auto':'badge-tecnologia',
  'social-networks':'badge-tecnologia',
  'health':'badge-saude','well-being':'badge-saude','fitness':'badge-saude',
  'personal-development':'badge-saude','motivational':'badge-saude','covid-19':'badge-saude',
  'education':'badge-educacao','courses-and-careers':'badge-educacao','works':'badge-educacao',
  'opinion':'badge-opiniao','editorial':'badge-opiniao','features':'badge-opiniao',
  'philosophy':'badge-opiniao',
  'environment':'badge-default','agriculture':'badge-default','bicentennial':'badge-default',
  'events':'badge-default','sports':'badge-default','soccer':'badge-default',
  'tennis':'badge-default','formula-1':'badge-default','cycling':'badge-default',
  'olympic-games':'badge-default','pan-american-games':'badge-default',
  'lifestyle':'badge-default','food':'badge-default','tourism-and-gastronomy':'badge-default',
  'fashion':'badge-default','beauty':'badge-default','pets':'badge-default',
  'religiosity':'badge-default','global-affairs':'badge-noticias',
};

function getCatLabel(slug) {
  const s = (slug||'').toLowerCase().trim();
  return CAT_LABEL_MAP[s] || s.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
}
function getCatBadge(slug) {
  const s = (slug||'').toLowerCase().trim();
  return CAT_BADGE_MAP[s] || 'badge-default';
}
